export type ListType = {
  listing_id: number,
  state: string,
  user_id: number,
  category_id: number,
  title: string,
  description: string,
  creation_tsz: number,
  ending_tsz: number,
  original_creation_tsz: number,
  last_modified_tsz: number,
  price: string,
  currency_code: string,
  quantity: number,
  sku?: Array<string>,
  tags: Array<string>,
  category_path: Array<string>,
  category_path_ids: Array<number>,
  materials: Array<string>,
  "shop_section_id": number,
  "featured_rank": null | number,
  "state_tsz": number,
  "url": string,
  "views": number,
  "num_favorers": number,
  "shipping_template_id": number,
  "processing_min": number,
  "processing_max": number,
  "who_made": string,
  "is_supply": boolean,
  "when_made": string,
  "item_weight": null | number,
  "item_weight_unit": string,
  "item_length": null | number,
  "item_width": null | number,
  "item_height": null | number,
  "item_dimensions_unit": string,
  "is_private": boolean,
  "recipient": null | string,
  "occasion": null | string,
  "style": null | Array<string>,
  "non_taxable": boolean,
  "is_customizable": boolean,
  "is_digital": boolean,
  "file_data": string,
  "should_auto_renew": boolean,
  "language": string,
  "has_variations": boolean,
  "taxonomy_id": number,
  "taxonomy_path": Array<string>,
  "used_manufacturer": boolean,
  "MainImage": {
    url_170x135: string
  }
}